MAKEFILE_DIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

RUN_TAG = $(shell ls librelane/runs/ | tail -n 1)
TOP = chip_top

PDK_ROOT ?= $(MAKEFILE_DIR)/gf180mcu
PDK ?= gf180mcuD
PDK_COMMIT ?= 019cf7a3e0de79bb0e4b6213758882d283c65816

# Available SCL libraries:
# gf180mcu_as_sc_mcu7t3v3
# gf180mcu_fd_sc_mcu7t5v0
# gf180mcu_fd_sc_mcu9t5v0
# gf180mcu_osu_sc_gp9t3v3 (broken)
# gf180mcu_osu_sc_gp12t3v3 (broken)

ifeq ($(SCL),default)
    SCL = gf180mcu_as_sc_mcu7t3v3
endif
SCL ?= gf180mcu_as_sc_mcu7t3v3

# Available PAD libraries:
# gf180mcu_fd_io
# gf180mcu_ocd_io

ifeq ($(PAD),default)
    PAD = gf180mcu_ocd_io
endif
PAD ?= gf180mcu_ocd_io

# Available SRAM macros:
# gf180mcu_fd_ip_sram
# gf180mcu_ocd_ip_sram

ifeq ($(SRAM),default)
    SRAM = gf180mcu_ocd_ip_sram
endif
SRAM ?= gf180mcu_ocd_ip_sram

ifeq ($(SRAM),gf180mcu_fd_ip_sram)
    MACROS = 5v
else
    MACROS = 3v3
endif

AVAILABLE_SLOTS = 1x1 0p5x1 1x0p5 0p5x0p5
DEFAULT_SLOT = 1x1

# Slot can be any of AVAILABLE_SLOTS
SLOT ?= $(DEFAULT_SLOT)

ifeq ($(SLOT),default)
    SLOT = $(DEFAULT_SLOT)
endif

ifeq ($(filter $(SLOT),$(AVAILABLE_SLOTS)),)
    $(error $(SLOT) does not exist in AVAILABLE_SLOTS: $(AVAILABLE_SLOTS))
endif

SLOT_DEFINE = SLOT_$(shell echo $(SLOT) | tr '[:lower:]' '[:upper:]')
SRAM_DEFINE = SRAM_$(SRAM)

LIBRELANE_OPTS = --pdk ${PDK} --pdk-root ${PDK_ROOT} --manual-pdk --scl ${SCL} --pad ${PAD}
LIBRELANE_CONFIGS = librelane/slots/slot_${SLOT}.yaml librelane/macros/macros_${MACROS}.yaml librelane/config.yaml

.DEFAULT_GOAL := help

help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Available targets:'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-20s %s\n", $$1, $$2}'
.PHONY: help

all: librelane ## Build the project (runs LibreLane)
.PHONY: all

$(PDK_ROOT)/ciel/gf180mcu/versions/$(PDK_COMMIT)/$(PDK):
	ciel enable $(PDK_COMMIT) --pdk-root $(PDK_ROOT) --pdk-family $(PDK) --include-libraries all

clone-pdk: $(PDK_ROOT)/ciel/gf180mcu/versions/$(PDK_COMMIT)/$(PDK) ## Clone the gf180mcu PDK
.PHONY: clone-pdk

# Need to find a better way to
# pass the variables to LibreLane
defines:
	@echo "Writing src/generated_defines.svh"
	$(file >src/generated_defines.svh,// This file is auto-generated by the Makefile)
	$(file >>src/generated_defines.svh,`define ${SLOT_DEFINE})
	$(file >>src/generated_defines.svh,`define ${SRAM_DEFINE})
.PHONY: defines

librelane: clone-pdk defines ## Run LibreLane flow (synthesis, PnR, verification)
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final
.PHONY: librelane

librelane-condensed: clone-pdk defines ## Run LibreLane flow (synthesis, PnR, verification)
	SRAM_DEFINE=${SRAM_DEFINE} librelane --condensed ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final
.PHONY: librelane-condensed

librelane-nodrc: clone-pdk defines ## Run LibreLane flow without DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip KLayout.Antenna --skip KLayout.DRC --skip Magic.DRC
.PHONY: librelane-nodrc

librelane-klayoutdrc: clone-pdk defines ## Run LibreLane flow without magic DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip Magic.DRC
.PHONY: librelane-klayoutdrc

librelane-magicdrc: clone-pdk defines ## Run LibreLane flow without KLayout DRC checks
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --save-views-to $(MAKEFILE_DIR)/final --skip KLayout.DRC
.PHONY: librelane-magicdrc

librelane-openroad: clone-pdk defines ## Open the last run in OpenROAD
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --last-run --flow OpenInOpenROAD
.PHONY: librelane-openroad

librelane-klayout: clone-pdk defines ## Open the last run in KLayout
	SRAM_DEFINE=${SRAM_DEFINE} librelane ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS} --last-run --flow OpenInKLayout
.PHONY: librelane-klayout

librelane-padring: clone-pdk defines ## Only create the padring
	python3 scripts/padring.py ${LIBRELANE_CONFIGS} ${LIBRELANE_OPTS}
.PHONY: librelane-padring

sim: clone-pdk defines ## Run RTL simulation with cocotb
	cd cocotb; PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 chip_top_tb.py
.PHONY: sim

sim-gl: clone-pdk defines ## Run gate-level simulation with cocotb (after copy-final)
	cd cocotb; GL=1 PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 chip_top_tb.py
.PHONY: sim-gl

sim-view: ## View simulation waveforms in GTKWave
	gtkwave cocotb/sim_build/chip_top.fst
.PHONY: sim-view

sim-sdram: ## Standalone SDRAM controller + open behavioral model test (iverilog, no PDK)
	mkdir -p cocotb/sim_build
	iverilog -g2012 -o cocotb/sim_build/tb_sdram \
		cocotb/models/tb_sdram.v \
		third_party/ultraembedded_axi_sdram_controller/src_v/sdram_axi.v \
		third_party/ultraembedded_axi_sdram_controller/src_v/sdram_axi_core.v \
		third_party/ultraembedded_axi_sdram_controller/src_v/sdram_axi_pmem.v \
		cocotb/models/sdram_sim.v
	vvp cocotb/sim_build/tb_sdram
.PHONY: sim-sdram

sim-bridge: clone-pdk defines ## Bridge a UDP socket to the sim so dma.py drives the simulated chip
	cd cocotb; TEST_MODULE=sim_udp_bridge PDK_ROOT=${PDK_ROOT} PDK=${PDK} SLOT=${SLOT} PAD=${PAD} SCL=${SCL} SRAM=${SRAM} python3 chip_top_tb.py
.PHONY: sim-bridge

ADPLL_TS  = cocotb/models/_sim_timescale.v
ADPLL_RTL = $(wildcard src/adpll/*.sv src/adpll/controller/*.sv src/adpll/dco/*.sv)
sim-adpll: ## Standalone digital ADPLL test: ring DCO (behavioural) + FLL lock (iverilog, no PDK)
	mkdir -p cocotb/sim_build
	iverilog -g2012 -o cocotb/sim_build/tb_adpll $(ADPLL_TS) $(ADPLL_RTL) cocotb/models/tb_adpll.v
	vvp cocotb/sim_build/tb_adpll
.PHONY: sim-adpll

sim-adpll-csr: ## Integrated ADPLL: program mul/div/enable over AXI4-Lite CSR, poll STATUS for lock (iverilog)
	mkdir -p cocotb/sim_build
	iverilog -g2012 -o cocotb/sim_build/tb_adpll_csr $(ADPLL_TS) \
		src/csr/adpll_csr.sv src/adpll/controller/adpll_controller_bangbang.sv src/adpll/adpll_freq_counter.sv \
		src/adpll/adpll_lock_detect.sv src/adpll/dco/ring_dco_binary.sv cocotb/models/tb_adpll_csr.v
	vvp cocotb/sim_build/tb_adpll_csr | grep -E "CSR programmed|LOCKED|PASS|FAIL"
.PHONY: sim-adpll-csr

sim-adpll-survey: ## Compare the ADPLL controller variants (bang-bang PI vs linear PI): lock time + code
	@mkdir -p cocotb/sim_build
	@for ctrl in "bang-bang:" "linear:-DCTRL_LINEAR"; do \
		name=$${ctrl%%:*}; def=$${ctrl#*:}; \
		echo "==== controller: $$name ===="; \
		iverilog -g2012 $$def -o cocotb/sim_build/tb_adpll_$$name $(ADPLL_TS) $(ADPLL_RTL) cocotb/models/tb_adpll.v && \
		vvp cocotb/sim_build/tb_adpll_$$name | grep -E "LOCKED|PASS|FAIL"; \
	done
.PHONY: sim-adpll-survey

sim-adpll-matrix: ## Verify ALL 6 ADPLL variants (2 controllers x 3 DCOs): lock time + settled tune
	@mkdir -p cocotb/sim_build
	@printf "%-26s %-12s %-8s %s\n" "config (ctrl x dco)" "lock_cyc" "tune" "result"
	@for ctrl in "bb:" "lin:-DCTRL_LINEAR"; do \
		for dco in "binary:" "therm:-DDCO_THERM" "muxtap:-DDCO_MUXTAP"; do \
			cn=$${ctrl%%:*}; cd=$${ctrl#*:}; dn=$${dco%%:*}; dd=$${dco#*:}; \
			iverilog -g2012 $$cd $$dd -o cocotb/sim_build/tb_mx_$${cn}_$${dn} $(ADPLL_TS) $(ADPLL_RTL) cocotb/models/tb_adpll.v 2>/dev/null && \
			out=$$(vvp cocotb/sim_build/tb_mx_$${cn}_$${dn} 2>/dev/null); \
			cyc=$$(echo "$$out" | grep -oE "lock_time=[0-9]+" | grep -oE "[0-9]+"); \
			tune=$$(echo "$$out" | grep -oE "tune=[0-9]+ in-range" | grep -oE "[0-9]+"); \
			res=$$(echo "$$out" | grep -oE "PASS|FAIL" | head -1); \
			printf "%-26s %-12s %-8s %s\n" "$$cn x $$dn" "$${cyc:-N/A}" "$${tune:-N/A}" "$${res:-NO-LOCK}"; \
		done; \
	done
.PHONY: sim-adpll-matrix

# ngspice >= 42 is required for the gf180 BSIM4 models (mulu0 et al); override NGSPICE
# to point at a new enough build if the default is too old.
NGSPICE ?= ngspice
dco-spice: clone-pdk ## Export ring_dco to SPICE and sweep tune codes through ngspice (freq-vs-code)
	python3 src/adpll/dco/gen_ring_dco_spice.py --pdk-root $(PDK_ROOT) --pdk $(PDK) --ngspice $(NGSPICE) \
		--bits 7 --sweep 0,4,8,16,32,64,96,127 --run --workdir cocotb/sim_build
.PHONY: dco-spice

# Corner DCO characterization uses the binary ring_dco (what gen_ring_dco_spice emits).
# DCO_BITS trims the ring for faster corner runs (the thermometer/muxtap variants share the
# same behavioural curve; their structural SPICE emitters are a follow-up).
DCO_BITS ?= 7
dco-spice-corners: clone-pdk ## DCO freq-vs-code across SS/TT/FF PVT corners (ngspice) -- run regularly
	@for corner in "ss 3.0 125" "typical 3.3 25" "ff 3.6 -40"; do \
		set -- $$corner; \
		echo "==== corner $$1 / $$2 V / $$3 C ===="; \
		python3 src/adpll/dco/gen_ring_dco_spice.py --pdk-root $(PDK_ROOT) --pdk $(PDK) --ngspice $(NGSPICE) \
			--bits $(DCO_BITS) --corner $$1 --vdd $$2 --temp $$3 \
			--sweep 0,16,32,64,96,127 --run --workdir cocotb/sim_build; \
	done
.PHONY: dco-spice-corners
